install_packages:
  - name: NetworkManager
  - name: bash-completion
  - name: vim-enhanced
  - name: firewalld

copy_files:
  - file: files/set_static_ip.sh
    remotepath: /home/automation/set_static_ip.sh

start_services:
  - name: NetworkManager
  - name: firewalld
