    - name: Install Packages
      package:
        name: "{{ item.name }}"
        state: present
      with_items: "{{ install_packages }}"

    - name: Start Services, if not started
      service:
        name: "{{ item.name }}"
        state: started
      with_items: "{{ start_services }}"